language: node_js

node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - make install

after_success:
  - cat build/tests/js/report/lcov.info | ./node_modules/.bin/coveralls

script:
  - make
