#!/usr/bin/env node
// vi:syntax=javascript

'use strict';

var screener = require('commander'),
    config = require('./config/config.json'),
    pkg = require('./package.json'),
    cli = require('./lib/cli');

screener
    .version(pkg.version)
    .option('-c, --config [file]', 'configuration file', config.DEFAULT_TESTS_FILE)
    .option('-o, --output [directory]', 'images are saved here', config.DEFAULT_OUT_DIR);

screener
    .command('build')
    .description('build tests')
    .action(cli.build(screener));

screener
    .command('show')
    .description('show tests information')
    .action(cli.show(screener));

screener.parse(process.argv);
