#!/bin/bash

source vendor/minond/expect/expect

[ -d build/snapshots ] && rm build/snapshots/*
node screener.js https://www.google.com/images/srpr/logo11w.png build/snapshots/google.png
node screener.js http://c2.com/ build/snapshots/c2.png

expect $(diff tests/snapshots/c2.png build/snapshots/c2.png) to pass
expect $(diff tests/snapshots/google.png build/snapshots/google.png) to pass
